services:
  keycloak:
    image: keycloak/keycloak:26.3
    ports:
      - "8080:8080"
      - "9002:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_CACHE_METRICS_ENABLED=true
      - KC_CACHE_METRICS_HISTOGRAMS_ENABLED=true
      - KC_FEATURES=user-event-metrics
      - KC_EVENT_METRICS_USER_ENABLED=true
      - KC_EVENT_METRICS_USER_EVENTS=login,logout,register,update_profile,refresh_token,invalid_signature,client_login,code_to_token,token_exchange
      - KC_EVENT_METRICS_USER_TAGS=realm,idp,clientId
      - KC_HTTP_METRICS_HISTOGRAMS_ENABLED=true
      - KC_HTTP_METRICS_SLOS=5,10,25,50,100,250,500,1000,2500,5000,10000
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - krakend
    volumes:
      - keycloak_data:/opt/keycloak/data

  krakend:
    image: krakend:2.10
    ports:
      - "8081:8080"
      - "9091:9090"
    volumes:
      - ./config/krakend:/etc/krakend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/__health"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: krakend
      GF_SECURITY_ADMIN_PASSWORD: krakend
      GF_AUT_ANONYMOUS_ENABLED: "true"
    volumes:
      - "./config/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml"
      - "./config/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml"
      - "./config/grafana/krakend:/var/lib/grafana/dashboards/krakend"
      - "./config/grafana/keycloak:/var/lib/grafana/dashboards/keycloak"
      - "grafana_data:/var/lib/grafana"

  permify:
    image: ghcr.io/permify/permify
    ports:
      - "3478:3478"
      - "3476:3476"
    volumes:
      - "./config/permify/config.yaml:/config"

  go-microservice:
    build:
      context: ./services/go-microservice
    ports:
      - "8082:8080"

volumes:
  keycloak_data:
  grafana_data:
